application: s~3idiotsflat
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /tasks/.*
  script: controllers.tasks.app
  login: admin

- url: /reminders.*
  script: controllers.reminders.app
  
- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on